[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn main:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[environments]
    [environments.development]
    ENV_EXAMPLE = "example"